### ISSUE TITLE
Remove Google Analytics from Theme Demo on Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [felicianotech/hugo-theme-lean-launch-page#12]
Hello @felicianotech 

As you might have noticed tracking is no longer accepted in theme demos on the Hugo website.

I was surprised to find out that your theme's demo comes with Google Analytics enabled.

Please do remove the UA ID from the Example Site's configuration and let me know.

Thank you.

cc: @digitalcraftsman

**Comment by felicianotech** [comment]
Hey @onedrawingperday,

The example config includes a UA ID because it's showing an example of how to use the theme. That ID isn't a real ID thus the loaded tracker can't actually track anything.

Instead of removing the ID, what I do for my personal themes is to not bother loading Google Analytics at all unless it's a production build.

Am I correct in that `HUGO_ENV` is not set when building theme sites in the Hugo Theme Directory? Or if it is set, that it's not set to "production"?

**Comment by onedrawingperday** [comment]
@felicianotech 

I noticed the GA tracking script being loaded in the demo and I saw that the UA ID is filled out.

But I didn't notice that it is a fake 1234 ID. 

Thanks for pointing it our and sorry for the noise.
